-   id: bazel-gazelle
    name: 'bazel run //:gazelle'
    description: This hook runs [Gazelle build generator](https://github.com/bazelbuild/bazel-gazelle)
    entry: run-bazel-gazelle.sh
    files: '\.go$'
    language: script
